import type { PullRequestFile } from "@/lib/github/diff";

/**
 * Why a file was triaged out of the AI review. Kept as a discriminated
 * reason rather than a boolean so the posted comment can say *what* was
 * skipped and why — "12 files skipped" with no reason reads as the bot
 * having quietly given up.
 */
export type SkipReason =
  | "whitespace-only"
  | "comment-only"
  | "import-order-only"
  | "file-deleted"
  | "generated"
  | "documentation";

export interface TriageResult {
  skip: SkipReason | undefined;
}

/** The +/- lines of a unified diff, with the leading marker removed. */
interface PatchLines {
  added: string[];
  removed: string[];
}

function splitPatch(patch: string): PatchLines {
  const added: string[] = [];
  const removed: string[] = [];

  for (const line of patch.split("\n")) {
    // "+++"/"---" are file headers, not content, and "\" is the
    // "no newline at end of file" marker.
    if (line.startsWith("+++") || line.startsWith("---") || line.startsWith("\\")) continue;
    if (line.startsWith("+")) added.push(line.slice(1));
    else if (line.startsWith("-")) removed.push(line.slice(1));
  }

  return { added, removed };
}

/**
 * Collapses a set of lines to comparable content.
 *
 * Joining before comparing (rather than comparing line by line) is what makes
 * this detect a reflow: a formatter splitting one long call across three
 * lines changes every line boundary while changing no code, and a line-wise
 * comparison would call that a real change.
 *
 * Trailing commas are dropped too, because that is the other half of what a
 * formatter does when it explodes a call across lines — prettier adds
 * `alpha,\n beta,\n)` where the original had `alpha, beta)`. A comma
 * immediately before a closing bracket is syntactically inert in JS/TS, so
 * ignoring it cannot mask a behavioral change; leaving it in would make this
 * rule miss the single most common formatting PR there is.
 */
function normalizeForComparison(lines: string[]): string {
  return lines
    .join("")
    .replace(/\s+/g, "")
    .replace(/,(?=[)\]}])/g, "");
}

/**
 * A whole-file reformat — a `prettier --write` across the repo being the
 * canonical case. This is the single highest-value triage rule: a 400-file
 * formatting PR is otherwise indistinguishable from 400 real changes, and
 * reviewing it costs the same.
 */
function isWhitespaceOnly({ added, removed }: PatchLines): boolean {
  if (added.length === 0 && removed.length === 0) return false;
  return normalizeForComparison(added) === normalizeForComparison(removed);
}

/**
 * Single-line and block comment markers for the languages this reviewer
 * supports (TypeScript and JavaScript — see the spec's out-of-scope list).
 * `#` is deliberately absent: in JS/TS it's a private class field, not a
 * comment, and treating `#count = 0` as a comment would skip real code.
 */
const COMMENT_LINE = /^\s*(\/\/|\/\*|\*\/|\*)/;

function isCommentOrBlank(line: string): boolean {
  return line.trim() === "" || COMMENT_LINE.test(line);
}

function isCommentOnly({ added, removed }: PatchLines): boolean {
  const all = [...added, ...removed];
  if (all.length === 0) return false;
  // Requires at least one actual comment line — an all-blank change is
  // whitespace, which the rule above already owns.
  if (!all.some((line) => COMMENT_LINE.test(line))) return false;
  return all.every(isCommentOrBlank);
}

const IMPORT_LINE = /^\s*(import\s|export\s+(\*|\{)[^;]*\sfrom\s)/;

/**
 * An import block that was sorted but not otherwise changed. Compares the
 * two sides as multisets, so a pure reorder matches while an added or
 * removed import does not — adding a dependency is a real change worth
 * reviewing even though every touched line is an import.
 */
function isImportOrderOnly({ added, removed }: PatchLines): boolean {
  const all = [...added, ...removed];
  if (all.length === 0) return false;
  if (!all.every((line) => line.trim() === "" || IMPORT_LINE.test(line))) return false;

  const normalize = (lines: string[]) =>
    lines
      .map((line) => line.trim())
      .filter((line) => line !== "")
      .sort();

  const a = normalize(added);
  const r = normalize(removed);
  return a.length === r.length && a.every((line, i) => line === r[i]);
}

/**
 * Text markers that generated files conventionally carry. Matched against
 * whatever text we already have — see shouldSkipFile's contract about never
 * fetching a file purely to run this check.
 */
const GENERATED_MARKER = /@generated|DO NOT EDIT|auto-generated|Code generated by/i;

export function hasGeneratedMarker(text: string): boolean {
  return GENERATED_MARKER.test(text);
}

/**
 * Decides whether a file's change is worth spending an AI call on. String
 * heuristics only — no model, no network. Every rule here is conservative in
 * the same direction: when a change is ambiguous it is REVIEWED, because
 * skipping a real change is a review failure while reviewing a trivial one
 * only costs tokens.
 *
 * `generatedText` is text already in hand that may carry a generated marker
 * — normally the patch itself. Deliberately not fetched: on a PR with 100
 * surviving files, a content fetch per file to check for `@generated` would
 * add 100 API calls before a single file gets reviewed, which is exactly the
 * cost this phase exists to avoid.
 */
/** Markdown docs — README, changelogs, design specs. Skipped by policy, not by content: a doc file is never noise, but the team has decided reviewing prose isn't worth the model call. */
const DOCUMENTATION_PATTERN = /\.(md|mdx)$/i;

export function triageFile(file: PullRequestFile, generatedText?: string): TriageResult {
  if (file.status === "removed") return { skip: "file-deleted" };
  if (DOCUMENTATION_PATTERN.test(file.filename)) return { skip: "documentation" };

  const text = generatedText ?? file.patch ?? "";
  // Only the top of the text is considered: these markers live in a header,
  // and scanning the whole body would match any file that merely discusses
  // code generation — this file included.
  if (text && hasGeneratedMarker(text.slice(0, 2000))) return { skip: "generated" };

  if (!file.patch) return { skip: undefined };

  const lines = splitPatch(file.patch);

  // Order matters: a formatter run that also reorders imports should read as
  // whitespace-only, the broader and more common explanation.
  if (isWhitespaceOnly(lines)) return { skip: "whitespace-only" };
  if (isCommentOnly(lines)) return { skip: "comment-only" };
  if (isImportOrderOnly(lines)) return { skip: "import-order-only" };

  return { skip: undefined };
}

const SKIP_LABELS: Record<SkipReason, string> = {
  "whitespace-only": "formatting/whitespace only",
  "comment-only": "comment changes only",
  "import-order-only": "import reordering only",
  "file-deleted": "file deleted",
  generated: "generated file",
  documentation: "documentation (.md)",
};

export function describeSkipReason(reason: SkipReason): string {
  return SKIP_LABELS[reason];
}
