/**
 * Scenario definitions for the large-PR runbook.
 *
 * Each scenario produces two file trees: a BASE state and a HEAD state. The
 * harness commits the base to one branch and the head to another, then opens
 * a PR between them — which is what makes files come back from GitHub with
 * status `modified` rather than `added`. A PR of purely added files exercises
 * a different (easier) path than the one these scenarios are meant to test.
 *
 * Sizes here are chosen to land on specific sides of the pipeline's real
 * thresholds (see REVIEW_CAPACITY in diff-selection.ts). If those constants
 * change, `predict.ts` will report the new expected values rather than these
 * comments going stale.
 */

export interface Scenario {
  id: number;
  slug: string;
  title: string;
  /** What this scenario is actually testing — printed in the report. */
  intent: string;
  /** Files as they exist on the PR's base branch. */
  base: Record<string, string>;
  /** Files as they exist on the PR's head branch. */
  head: Record<string, string>;
  /** Scenario 4 layers a second push onto an already-reviewed PR. */
  followUp?: Record<string, string>;
  expect: {
    /** Whether the size gate should refuse this PR outright. */
    bails: boolean;
    /** Zero LLM calls expected (either a bail, or nothing survived filtering). */
    zeroLlmCalls: boolean;
    notes: string[];
  };
}

/** A plausible TypeScript module of roughly `lines` lines. */
function sourceFile(name: string, lines: number, variant: number): string {
  const out = [
    `// ${name} — generated fixture for the large-PR verification runbook`,
    `export interface Config${variant} {`,
    `  retries: number;`,
    `  timeoutMs: number;`,
    `}`,
    ``,
  ];
  for (let i = 0; i < lines; i++) {
    out.push(`export function handler${variant}_${i}(input: number): number {`);
    out.push(`  const scaled = input * ${variant + i + 1};`);
    out.push(`  return scaled > 0 ? scaled : ${variant};`);
    out.push(`}`);
  }
  return out.join("\n") + "\n";
}

/** The same module with every function body changed — a real diff, not a reformat. */
function sourceFileChanged(name: string, lines: number, variant: number): string {
  const out = [
    `// ${name} — generated fixture for the large-PR verification runbook`,
    `export interface Config${variant} {`,
    `  retries: number;`,
    `  timeoutMs: number;`,
    `}`,
    ``,
  ];
  for (let i = 0; i < lines; i++) {
    out.push(`export function handler${variant}_${i}(input: number): number {`);
    out.push(`  const scaled = input * ${variant + i + 2};`);
    out.push(`  return scaled >= 0 ? scaled + 1 : ${variant + 1};`);
    out.push(`}`);
  }
  return out.join("\n") + "\n";
}

function tree(
  count: number,
  make: (name: string, index: number) => string,
  prefix = "src/mod",
): Record<string, string> {
  const files: Record<string, string> = {};
  for (let i = 0; i < count; i++) {
    const name = `${prefix}${i}.ts`;
    files[name] = make(name, i);
  }
  return files;
}

/** A lockfile large enough to dominate the diff if it were ever reviewed. */
function lockfile(entries: number, bump: number): string {
  const deps: Record<string, unknown> = {};
  for (let i = 0; i < entries; i++) {
    deps[`node_modules/pkg-${i}`] = {
      version: `1.0.${i + bump}`,
      resolved: `https://registry.npmjs.org/pkg-${i}/-/pkg-${i}-1.0.${i + bump}.tgz`,
      integrity: `sha512-${"a".repeat(40)}${i}`,
    };
  }
  return JSON.stringify({ name: "fixture", lockfileVersion: 3, packages: deps }, null, 2) + "\n";
}

function generatedFile(lines: number, bump: number): string {
  const out = [
    "// Code generated by protoc-gen-ts. DO NOT EDIT.",
    "// @generated",
    "",
  ];
  for (let i = 0; i < lines; i++) out.push(`export const FIELD_${i} = ${i + bump};`);
  return out.join("\n") + "\n";
}

export const SCENARIOS: Scenario[] = [
  {
    id: 1,
    slug: "all-real",
    title: "90 files, entirely legitimate code changes, no noise",
    intent:
      "The case the old fixed changed-line cutoff wrongly refused. Nothing filters out, so this is the most expensive legitimate review the bot will run.",
    base: tree(90, (n, i) => sourceFile(n, 12, i)),
    head: tree(90, (n, i) => sourceFileChanged(n, 12, i)),
    expect: {
      bails: false,
      zeroLlmCalls: false,
      notes: [
        "Every file should be reviewed; coverage should be high.",
        "Inline comments must be capped at 25 with the remainder in a collapsed section.",
      ],
    },
  },
  {
    id: 2,
    slug: "mixed-noise",
    title: "Same size, with a lockfile bump, a generated file and build output mixed in",
    intent:
      "Confirms filtering happens BEFORE the size gate, so noise cannot push a reviewable PR over a limit.",
    base: {
      ...tree(60, (n, i) => sourceFile(n, 12, i)),
      "package-lock.json": lockfile(400, 0),
      "src/api.generated.ts": generatedFile(300, 0),
      ...tree(20, (n, i) => sourceFile(n, 40, i), "dist/bundle"),
    },
    head: {
      ...tree(60, (n, i) => sourceFileChanged(n, 12, i)),
      "package-lock.json": lockfile(400, 1),
      "src/api.generated.ts": generatedFile(300, 1),
      ...tree(20, (n, i) => sourceFileChanged(n, 40, i), "dist/bundle"),
    },
    expect: {
      bails: false,
      zeroLlmCalls: false,
      notes: [
        "The lockfile, the .generated.ts file and everything under dist/ must be filtered.",
        "The summary must state how many files were skipped and why.",
      ],
    },
  },
  {
    id: 3,
    slug: "giant-single-file",
    title: "One file with a diff large enough that GitHub returns patch: null",
    intent:
      "The Phase 1 bug: before the local-diff fallback, this file was dropped silently and appeared in no 'unreviewed' list.",
    base: { "src/huge.ts": sourceFile("src/huge.ts", 2000, 1) },
    head: { "src/huge.ts": sourceFileChanged("src/huge.ts", 2000, 1) },
    expect: {
      bails: false,
      zeroLlmCalls: false,
      notes: [
        "Check the raw API first: `gh api repos/OWNER/REPO/pulls/N/files --jq '.[].patch'` should be null.",
        "The review must still cover the file (patchSource 'local') or say 'no obtainable diff' — never omit it.",
      ],
    },
  },
  {
    id: 4,
    slug: "follow-up",
    title: "A 2-line follow-up push to an already-reviewed PR",
    intent: "Incremental review: only the delta since lastReviewedSha should reach the model.",
    base: tree(50, (n, i) => sourceFile(n, 12, i)),
    head: tree(50, (n, i) => sourceFileChanged(n, 12, i)),
    followUp: {
      // One file, two changed lines, on top of the already-reviewed head.
      "src/mod3.ts": sourceFileChanged("src/mod3.ts", 12, 3).replace(
        "export function handler3_0(input: number): number {",
        "export function handler3_0(input: number): number {\n  // follow-up change under test",
      ),
    },
    expect: {
      bails: false,
      zeroLlmCalls: false,
      notes: [
        "The SECOND review is the one under test: it should be ~2 LLM calls, not 51.",
        "Its token count should be a small fraction of the first review's.",
      ],
    },
  },
  {
    id: 5,
    slug: "pure-build-output",
    title: "400 files of pure build output",
    intent: "Everything filters out, so the bot must spend nothing at all.",
    base: tree(400, (n, i) => sourceFile(n, 30, i), "dist/chunk"),
    head: tree(400, (n, i) => sourceFileChanged(n, 30, i), "dist/chunk"),
    expect: {
      bails: false,
      zeroLlmCalls: true,
      notes: [
        "This is NOT a bail-out — it is 'nothing to review'. Both post a comment; only one is a refusal.",
        "metrics.calls must be exactly 0.",
      ],
    },
  },
  {
    id: 6,
    slug: "coverage-ceiling",
    title: "330 real files — sized to sit just under the coverage floor",
    intent: "Checks the bail-out comment reads clearly and shows real numbers, not just 'too large'.",
    base: tree(330, (n, i) => sourceFile(n, 20, i)),
    head: tree(330, (n, i) => sourceFileChanged(n, 20, i)),
    expect: {
      bails: true,
      zeroLlmCalls: true,
      notes: [
        "Expect reason 'coverage-too-low'.",
        "The comment must show files changed, files after filtering, capacity and projected cost.",
        "It must offer `@prsentry review --force`.",
      ],
    },
  },
];

export function scenarioById(id: number): Scenario {
  const found = SCENARIOS.find((s) => s.id === id);
  if (!found) throw new Error(`no scenario ${id} (have ${SCENARIOS.map((s) => s.id).join(", ")})`);
  return found;
}
