import { describe, it, expect } from "vitest";
import { triageFile } from "@/lib/review/triage";
import type { PullRequestFile } from "@/lib/github/diff";

function file(patch: string, overrides: Partial<PullRequestFile> = {}): PullRequestFile {
  return { filename: "src/a.ts", status: "modified", patch, ...overrides };
}

describe("triageFile", () => {
  it("skips a pure re-indentation", () => {
    const patch = ["@@ -1,2 +1,2 @@", "-function a() {", "-  return 1;", "+function a() {", "+    return 1;"].join("\n");

    expect(triageFile(file(patch)).skip).toBe("whitespace-only");
  });

  it("skips a formatter reflow that moves code across line boundaries", () => {
    // The prettier case: same tokens, different line breaks. A line-by-line
    // comparison would call this a real change.
    const patch = [
      "@@ -1,2 +1,4 @@",
      "-doSomething(alpha, beta, gamma);",
      "+doSomething(",
      "+  alpha,",
      "+  beta,",
      "+  gamma,",
      "+);",
    ].join("\n");

    expect(triageFile(file(patch)).skip).toBe("whitespace-only");
  });

  it("reviews a change that alters an identifier even if the formatting also changed", () => {
    const patch = ["@@ -1,1 +1,1 @@", "-doSomething(alpha);", "+doSomething( beta );"].join("\n");

    expect(triageFile(file(patch)).skip).toBeUndefined();
  });

  it("skips a comment-only change", () => {
    const patch = ["@@ -1,2 +1,2 @@", "-// old note", "+// new note, clarified"].join("\n");

    expect(triageFile(file(patch)).skip).toBe("comment-only");
  });

  it("skips a block-comment edit", () => {
    const patch = ["@@ -1,3 +1,3 @@", "-/*", "- * old", "- */", "+/*", "+ * new", "+ */"].join("\n");

    expect(triageFile(file(patch)).skip).toBe("comment-only");
  });

  it("does not treat a private class field as a comment", () => {
    // `#count` is real code in JS/TS, not a shell comment.
    const patch = ["@@ -1,1 +1,1 @@", "-  #count = 0;", "+  #count = 1;"].join("\n");

    expect(triageFile(file(patch)).skip).toBeUndefined();
  });

  it("skips a pure import reorder", () => {
    const patch = [
      "@@ -1,3 +1,3 @@",
      "-import b from 'b';",
      "-import a from 'a';",
      "+import a from 'a';",
      "+import b from 'b';",
    ].join("\n");

    expect(triageFile(file(patch)).skip).toBe("import-order-only");
  });

  it("reviews an import block that gained a dependency", () => {
    const patch = [
      "@@ -1,2 +1,3 @@",
      "-import a from 'a';",
      "+import a from 'a';",
      "+import evil from 'evil';",
    ].join("\n");

    expect(triageFile(file(patch)).skip).toBeUndefined();
  });

  it("skips a deleted file", () => {
    expect(triageFile(file("", { status: "removed" })).skip).toBe("file-deleted");
  });

  it("skips a file whose patch carries a generated marker", () => {
    const patch = ["@@ -1,2 +1,2 @@", "+// @generated by protoc. DO NOT EDIT.", "+export const x = 1;"].join("\n");

    expect(triageFile(file(patch)).skip).toBe("generated");
  });

  it("matches the other conventional generated markers", () => {
    for (const marker of ["DO NOT EDIT", "auto-generated", "Code generated by protoc-gen-go"]) {
      const patch = `@@ -1,1 +1,1 @@\n+// ${marker}\n+const x = 1;`;
      expect(triageFile(file(patch)).skip).toBe("generated");
    }
  });

  it("does not treat a file that merely mentions generation deep in the body as generated", () => {
    const filler = Array.from({ length: 200 }, (_, i) => `+const line${i} = ${i};`).join("\n");
    const patch = `@@ -1,200 +1,200 @@\n${filler}\n+// this function handles @generated files`;

    expect(triageFile(file(patch)).skip).toBeUndefined();
  });

  it("reviews an ordinary code change", () => {
    const patch = ["@@ -1,1 +1,1 @@", "-const timeout = 30;", "+const timeout = 60;"].join("\n");

    expect(triageFile(file(patch)).skip).toBeUndefined();
  });

  it("uses separately supplied text for the generated check when given it", () => {
    const patch = ["@@ -400,1 +400,1 @@", "-const x = 1;", "+const x = 2;"].join("\n");

    // The patch is a deep hunk with no header, but the caller already had the
    // file's content (from the patch:null fallback) and passes it in.
    expect(triageFile(file(patch), "// Code generated by thing. DO NOT EDIT.\n").skip).toBe("generated");
  });
});

describe("markdown documentation", () => {
  it("skips a .md file regardless of its content", () => {
    const patch = ["@@ -1,2 +1,2 @@", "-old prose", "+entirely different prose, a real edit"].join("\n");
    expect(triageFile(file(patch, { filename: "README.md" })).skip).toBe("documentation");
  });

  it("skips .mdx too", () => {
    expect(triageFile(file("@@ -1,1 +1,1 @@\n-a\n+b", { filename: "docs/guide.mdx" })).skip).toBe("documentation");
  });

  it("does not skip a file that merely contains 'md' in its name", () => {
    const patch = ["@@ -1,1 +1,1 @@", "-const x = 1;", "+const x = 2;"].join("\n");
    expect(triageFile(file(patch, { filename: "src/markdown-renderer.ts" })).skip).toBeUndefined();
  });
});
